#!/usr/bin/env python3
"""Weekly digest of wiki feedback signals.

Reads the past 7 days of gap rows from the auditlog Table, groups them by
kind, and opens a single GitHub issue listing 👎 events and unanswered
questions. Skips opening the issue if there's nothing to report.

Required env:
    AZURE_STORAGE_ACCOUNT  Storage account holding the auditlog table
    GITHUB_REPOSITORY      e.g. GauravShah-TomTom/knowledge-base-wiki
    GH_TOKEN               Token with `issues: write` on the repo
Optional:
    DIGEST_DAYS            Window in days (default 7)
    DIGEST_LABELS          Comma-separated labels (default "wiki-feedback,wiki-gap")
"""
from __future__ import annotations

import datetime
import json
import os
import subprocess
import sys
from collections import Counter, defaultdict
from typing import Any

from azure.data.tables import TableServiceClient
from azure.identity import DefaultAzureCredential


TABLE_NAME = "auditlog"


def date_window(days: int) -> tuple[str, str, str]:
    """Returns (start_iso_date, end_iso_date, label) — both inclusive, UTC."""
    today = datetime.datetime.now(datetime.timezone.utc).date()
    start = today - datetime.timedelta(days=days - 1)
    return start.isoformat(), today.isoformat(), today.isoformat()


def fetch_gap_rows(start_date: str, end_date: str) -> list[dict[str, Any]]:
    account = os.environ["AZURE_STORAGE_ACCOUNT"]
    credential = DefaultAzureCredential()
    service = TableServiceClient(
        endpoint=f"https://{account}.table.core.windows.net",
        credential=credential,
    )
    table = service.get_table_client(TABLE_NAME)

    flt = (
        f"PartitionKey ge '{start_date}' and PartitionKey le '{end_date}' "
        "and (kind eq 'gap_no_hits' or kind eq 'gap_negative_feedback')"
    )
    return [dict(e) for e in table.query_entities(flt)]


def build_body(rows: list[dict[str, Any]], start_date: str, end_date: str) -> str:
    by_kind: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for r in rows:
        by_kind[r.get("kind", "")].append(r)

    neg = by_kind.get("gap_negative_feedback", [])
    nohits = by_kind.get("gap_no_hits", [])

    lines: list[str] = []
    lines.append(f"_Window: **{start_date} → {end_date}** (UTC, 7 days)._")
    lines.append("")
    lines.append(
        f"**Summary:** {len(rows)} gap event(s) — "
        f"{len(neg)} 👎, {len(nohits)} unanswered questions."
    )
    lines.append("")

    # 👎 section — each event is one bullet
    if neg:
        lines.append("## 👎 Negative feedback")
        lines.append("")
        for r in neg:
            q = (r.get("question") or "").strip()
            try:
                citations = json.loads(r.get("citations") or "[]")
            except json.JSONDecodeError:
                citations = []
            cites = ", ".join(f"`{c}`" for c in citations) or "_(no citations recorded)_"
            lines.append(f"- **Q:** {q}\n  Cited: {cites}")
        lines.append("")

    # No-hits section — group by exact normalised text, descending count
    if nohits:
        questions = Counter((r.get("question") or "").strip().lower() for r in nohits)
        lines.append("## ❓ Unanswered questions (no wiki hits)")
        lines.append("")
        for q, count in questions.most_common(20):
            if not q:
                continue
            suffix = f" — asked **{count}×**" if count > 1 else ""
            lines.append(f"- {q}{suffix}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append(
        "Auto-generated by `.github/workflows/wiki-feedback-digest.yml`. "
        "Close this issue when the listed gaps are addressed (new pages written, "
        "stale pages fixed). The next digest opens next Monday."
    )
    return "\n".join(lines)


def open_issue(title: str, body: str, labels: list[str]) -> str:
    repo = os.environ["GITHUB_REPOSITORY"]
    cmd = [
        "gh", "issue", "create",
        "--repo", repo,
        "--title", title,
        "--body", body,
        "--label", ",".join(labels),
    ]
    out = subprocess.check_output(cmd, text=True).strip()
    return out


def main() -> int:
    days = int(os.environ.get("DIGEST_DAYS", "7"))
    labels = [s.strip() for s in os.environ.get("DIGEST_LABELS", "wiki-feedback,wiki-gap").split(",") if s.strip()]
    start_date, end_date, week_label = date_window(days)

    print(f"Reading gap rows: {start_date} → {end_date}", file=sys.stderr)
    rows = fetch_gap_rows(start_date, end_date)
    print(f"Found {len(rows)} gap row(s).", file=sys.stderr)

    if not rows:
        print("Nothing to digest — skipping issue creation.")
        return 0

    body = build_body(rows, start_date, end_date)
    title = f"Wiki feedback digest — week ending {week_label}"
    url = open_issue(title, body, labels)
    print(f"Opened issue: {url}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
